# fly.toml app configuration file generated for outlearn-edu on 2024-12-27T19:16:22+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'outlearn-edu'
org = "outlearn"
primary_region = 'syd'

[build]

[deploy]
strategy = 'immediate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/up"
protocol = "http"
timeout = "2s"
tls_skip_verify = false
headers = {}

[[vm]]
  memory = '768mb'
  cpu_kind = 'shared'
  cpus = 1
