name: Deploy to Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FLY_PROJECT_NAME: outlearn-edu
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
  ENV_FILE_PATH: .env.prod
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only

  sync-secrets:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: bun install
      - run: bun run scripts/set-remote-secrets.ts
